// Wheel Micro-Simulation — Back-EMF / Push-Back Edition
(function () {
    const WheelSim = Object.assign({}, window.MicroRenderer, {
        wheelBody: null,
        nozzle: [],
        shroud: null,
        subSteps: 4,
        rpm: 0,
        smoothedRpm: 0,

        // Back-EMF educational metrics
        backEMF: 0,         // Voltage generated by spinning wheel (0-100)
        effectiveCurrent: 0, // Net current after back-EMF subtraction
        loadTorque: 30,      // Mechanical load on the shaft (0-100)

        start: function () {
            this.initEngine();
            const canvas = document.getElementById('simulationCanvas');
            this.setupCommonScene(canvas.width, canvas.height);

            const cx = canvas.width / 2;
            const cy = canvas.height / 2;

            this.createWheelBody(cx, cy);
            this.createNozzle(cx, cy);

            Matter.Body.setInertia(this.wheelBody, this.wheelBody.inertia * 0.45);

            this.activeMode = 'micro-wheel';
            this.injectLoadSlider();

            Matter.Events.on(this.engine, 'beforeUpdate', () => {
                this.applyWheelForce(canvas.width, canvas.height / 2);
                this.applyBackEMF(canvas.width / 2);
                this.applyLoadTorque();
                this.wrapAndTurbulateParticles(canvas.width, canvas.height / 2);
                this.tuneParticlePhysics();
                this.updateStats();
            });
        },

        /* ── Load Torque UI ─────────────────────────────── */
        injectLoadSlider: function () {
            const panel = document.querySelector('.control-panel');
            if (!panel) return;

            const group = document.createElement('div');
            group.className = 'control-group';
            group.innerHTML = `
                <label for="loadSlider">Mechanical Load (Torque)</label>
                <div class="slider-wrapper">
                    <input type="range" id="loadSlider" min="0" max="100" value="${this.loadTorque}">
                    <span id="loadValue" class="value-readout">${this.loadTorque}%</span>
                </div>
            `;
            // Insert before the metrics dashboard
            const metrics = panel.querySelector('.metrics-dashboard');
            if (metrics) panel.insertBefore(group, metrics);
            else panel.appendChild(group);

            const slider = document.getElementById('loadSlider');
            const readout = document.getElementById('loadValue');
            slider.addEventListener('input', (e) => {
                this.loadTorque = parseInt(e.target.value);
                readout.innerText = `${this.loadTorque}%`;
            });
        },

        /* ── Stats ──────────────────────────────────────── */
        updateStats: function () {
            // Calculate a more realistic RPM representation
            const rawRpm = Math.abs(this.wheelBody.angularVelocity * 60 / (Math.PI * 2)) * 60;
            // Visual multiplier for UI
            const currentRpm = Math.abs(this.wheelBody.angularVelocity) * 1200;
            
            this.smoothedRpm = this.smoothedRpm * 0.9 + currentRpm * 0.1;
            this.rpm = Math.round(this.smoothedRpm);

            const supplyV = State.pumpPressure;
            
            // Back EMF is strictly proportional to motor speed
            // Kv represents the motor's voltage constant (V per RPM)
            const Kv = 0.45;
            // Cap Back-EMF at 99% of supply voltage so it doesn't exceed the driving force
            this.backEMF = Math.min(supplyV * 0.99, this.smoothedRpm * Kv);
            
            // I_eff = (V_supply - V_backEMF) / R
            const resistance = 5 + ((100 - State.valveOpenness) * 2);
            const netVoltage = Math.max(0, supplyV - this.backEMF);
            this.effectiveCurrent = (netVoltage / resistance) * 10;
        },

        /* ── Physics ────────────────────────────────────── */
        applyFluidCohesion: function () {
            const particles = this.particles;
            const radius = this.PARTICLE_RADIUS;
            const threshold = radius * 2.8;
            const thresholdSq = threshold * threshold;
            const cohesionMag = 0.00018;

            const sorted = [...particles].sort((a, b) => a.position.x - b.position.x);

            for (let i = 0; i < sorted.length; i++) {
                const p1 = sorted[i];
                for (let j = i + 1; j < sorted.length; j++) {
                    const p2 = sorted[j];
                    const dx = p2.position.x - p1.position.x;
                    if (dx > threshold) break;

                    const dy = p2.position.y - p1.position.y;
                    const distSq = dx * dx + dy * dy;

                    if (distSq < thresholdSq && distSq > 1) {
                        const dist = Math.sqrt(distSq);
                        const force = (threshold - dist) * cohesionMag;
                        const fx = (dx / dist) * force;
                        const fy = (dy / dist) * force;

                        Matter.Body.applyForce(p1, p1.position, { x: fx, y: fy });
                        Matter.Body.applyForce(p2, p2.position, { x: -fx, y: -fy });
                    }
                }
            }
        },

        wrapAndTurbulateParticles: function (w, pipeY) {
            this.wrapParticles(w, pipeY);
            const cx = w / 2;
            for (const p of this.particles) {
                if (p.position.x > cx + 50 && p.position.x < cx + 250) {
                    const jitter = (Math.random() - 0.5) * 1.5;
                    Matter.Body.applyForce(p, p.position, { x: 0, y: jitter * 0.0002 });
                }
            }
        },

        createNozzle: function (cx, cy) {
            const { Bodies, Composite } = Matter;
            const nozzleOptions = { isStatic: true, collisionFilter: { category: 0x0002 } };

            const walls = [];
            const segments = 8;
            const nozzleWidth = 140;
            const entryY = 85;
            const exitYTop = 65;
            const exitYBottom = 5;

            for (let i = 0; i < segments; i++) {
                const t = i / (segments - 1);
                const x = cx - 230 + t * nozzleWidth;
                const topWallY = cy - (entryY - t * (entryY - exitYTop));
                walls.push(Bodies.rectangle(x, topWallY, 25, 12, { ...nozzleOptions, angle: Math.PI / 12 }));
                const bottomWallY = cy + (entryY - t * (entryY + exitYBottom));
                walls.push(Bodies.rectangle(x, bottomWallY, 25, 12, { ...nozzleOptions, angle: -Math.PI / 8 }));
            }

            const shroudVertices = [
                { x: 0, y: 0 }, { x: 60, y: 0 }, { x: 60, y: 15 }, { x: 25, y: 45 }, { x: 0, y: 45 }
            ];
            this.shroud = Bodies.fromVertices(cx - 75, cy + 68, [shroudVertices], { ...nozzleOptions });

            this.nozzle = walls;
            Composite.add(this.engine.world, [...this.nozzle, this.shroud]);
        },

        createWheelBody: function (cx, wheelY) {
            const { Bodies, Body, Composite, Constraint } = Matter;
            const NUM_BLADES = 6;
            const INNER_RADIUS = 20;
            const BLADE_LENGTH = 38;
            const BLADE_WIDTH = 10;

            const parts = [];
            parts.push(Bodies.circle(cx, wheelY, INNER_RADIUS, {}));

            for (let i = 0; i < NUM_BLADES; i++) {
                const angle = (i / NUM_BLADES) * Math.PI * 2;
                const bx = cx + Math.cos(angle) * (INNER_RADIUS + BLADE_LENGTH / 2);
                const by = wheelY + Math.sin(angle) * (INNER_RADIUS + BLADE_LENGTH / 2);

                const blade = Bodies.rectangle(bx, by, BLADE_LENGTH, BLADE_WIDTH, {
                    angle: angle,
                    density: 0.035, // Heavier to increase inertia and give realistic spool-up
                    frictionAir: 0.005,
                    friction: 0.1,
                    restitution: 0.2
                });
                parts.push(blade);
            }

            const wheelBody = Body.create({
                parts,
                isStatic: false,
                density: 0.025,
                frictionAir: 0.01,
                friction: 0.1,
                collisionFilter: { category: 0x0004, mask: 0x0001 },
            });

            Body.setPosition(wheelBody, { x: cx, y: wheelY });
            const pin = Constraint.create({
                pointA: { x: cx, y: wheelY },
                bodyB: wheelBody,
                pointB: { x: 0, y: 0 },
                stiffness: 1,
                length: 0,
            });
            Composite.add(this.engine.world, [wheelBody, pin]);
            this.wheelBody = wheelBody;
        },

        tuneParticlePhysics: function () {
            for (const p of this.particles) {
                p.restitution = 0.45;
                p.density = 0.0045;
                p.friction = 0;
            }
        },

        applyWheelForce: function (w, pipeY) {
            const supplyV = State.pumpPressure;
            const valveScale = State.valveOpenness / 100;
            
            // Base flow from pump pushing water forwards
            const forceMag = (supplyV * 0.0012 * valveScale) / this.subSteps;
            const maxSpeed = supplyV * 0.22 * valveScale;

            for (const p of this.particles) {
                if (forceMag > 0) Matter.Body.applyForce(p, p.position, { x: forceMag, y: 0 });
                const speed = Math.sqrt(p.velocity.x ** 2 + p.velocity.y ** 2);
                if (speed > maxSpeed) {
                    const s = maxSpeed / speed;
                    Matter.Body.setVelocity(p, { x: p.velocity.x * s, y: p.velocity.y * s });
                }
            }
        },

        applyBackEMF: function (cx) {
            // V_backEMF pushes water backward from the motor side
            if (this.backEMF <= 0.5) return;
            
            const valveScale = State.valveOpenness / 100;
            // The backward push force is proportional to backEMF
            const backForceMag = (this.backEMF * 0.0012 * valveScale) / this.subSteps;

            for (const p of this.particles) {
                const dx = cx - p.position.x;
                // Apply push back upstream of the wheel (dx > 20 and dx < 300)
                if (dx > 20 && dx < 300) {
                    const proximity = 1 - ((dx - 20) / 280);

                    // Push particles left (against pump flow)
                    const fx = -backForceMag * proximity;
                    const dy = p.position.y - this.wheelBody.position.y;
                    const fy = Math.sign(dy) * backForceMag * proximity * 0.1;

                    Matter.Body.applyForce(p, p.position, { x: fx, y: fy });

                    // Tag for red visual rendering
                    p.isPushedBack = (p.velocity.x < 0 && proximity > 0.2);
                } else {
                    p.isPushedBack = false;
                }
            }
        },

        applyLoadTorque: function () {
            // Mechanical load opposes rotation — higher load = more braking
            const loadFactor = this.loadTorque / 100;
            let angVel = this.wheelBody.angularVelocity;

            if (loadFactor >= 1.0) {
                // Completely stop the wheel when load is full (100%)
                Matter.Body.setAngularVelocity(this.wheelBody, 0);
                this.wheelBody.torque = 0;
                return;
            }

            // Braking torque exponentially increases with load
            const brakingTorque = -angVel * Math.pow(loadFactor, 2) * 0.015;
            this.wheelBody.torque += brakingTorque;

            // Static friction at high load when nearly stopped
            if (loadFactor > 0.7 && Math.abs(angVel) < 0.05) {
                Matter.Body.setAngularVelocity(this.wheelBody, angVel * 0.5);
            }
        },

        /* ── Rendering ──────────────────────────────────── */
        draw: function (ctx, canvas, state) {
            this.drawBackground(ctx, canvas);
            this.drawPipe(ctx, canvas);
            this.drawPressureZone(ctx, canvas);
            this.drawHousing(ctx, canvas);
            this.drawParticles(ctx, canvas);
            this.drawNozzle(ctx);
            this.drawWheel(ctx, this.wheelBody.position.x, this.wheelBody.position.y);
            this.drawBackEMFArrows(ctx, canvas);
            this.drawHUD(ctx, canvas);
        },

        drawPressureZone: function (ctx, canvas) {
            // Visualise upstream pressure buildup from back-EMF
            const cx = canvas.width / 2;
            const cy = canvas.height / 2;
            const intensity = Math.min(1, this.backEMF / Math.max(1, State.pumpPressure));
            if (intensity < 0.05) return;

            const pt = this.PIPE_THICKNESS;
            const wv = this.WALL_VISUAL;
            const innerTop = cy - pt / 2 + wv / 2 + wv / 2;
            const innerBottom = cy + pt / 2 - wv / 2 - wv / 2;

            // Red-orange pressure glow upstream of wheel
            const grad = ctx.createLinearGradient(cx - 300, 0, cx - 40, 0);
            grad.addColorStop(0, `rgba(248, 113, 113, 0)`);
            grad.addColorStop(0.4, `rgba(248, 113, 113, ${intensity * 0.08})`);
            grad.addColorStop(1, `rgba(248, 113, 113, ${intensity * 0.2})`);
            ctx.fillStyle = grad;
            ctx.fillRect(cx - 300, innerTop, 260, innerBottom - innerTop);
        },

        drawBackEMFArrows: function (ctx, canvas) {
            const cx = canvas.width / 2;
            const cy = canvas.height / 2;
            const intensity = Math.min(1, this.backEMF / Math.max(1, State.pumpPressure));
            if (intensity < 0.08) return;

            ctx.save();
            // Animate arrow position
            const time = Date.now() / 800;
            const alpha = intensity * 0.6;

            // Draw 3 push-back arrows upstream of wheel
            for (let i = 0; i < 3; i++) {
                const baseX = cx - 80 - i * 55;
                const offset = ((time + i * 1.2) % 2) * -20; // slide leftward
                const x = baseX + offset;
                const arrowAlpha = alpha * (1 - i * 0.25);

                ctx.strokeStyle = `rgba(248, 113, 113, ${arrowAlpha})`;
                ctx.fillStyle = `rgba(248, 113, 113, ${arrowAlpha})`;
                ctx.lineWidth = 2.5;

                // Arrow shaft
                ctx.beginPath();
                ctx.moveTo(x + 20, cy);
                ctx.lineTo(x, cy);
                ctx.stroke();

                // Arrow head pointing left
                ctx.beginPath();
                ctx.moveTo(x, cy);
                ctx.lineTo(x + 8, cy - 6);
                ctx.lineTo(x + 8, cy + 6);
                ctx.closePath();
                ctx.fill();
            }
            ctx.restore();
        },

        drawParticles: function (ctx, canvas) {
            const pipeY = canvas.height / 2;
            const pt = this.PIPE_THICKNESS;
            const wv = this.WALL_VISUAL;
            const innerTop = pipeY - pt / 2 + wv / 2;
            const innerBottom = pipeY + pt / 2 - wv / 2;
            const visLeft = canvas.width / 2 - this.VISIBLE_WIDTH / 2;
            const visRight = canvas.width / 2 + this.VISIBLE_WIDTH / 2;

            ctx.save();
            ctx.beginPath();
            ctx.rect(visLeft, innerTop + wv / 2, this.VISIBLE_WIDTH, innerBottom - innerTop - wv);
            ctx.clip();

            for (let p of this.particles) {
                ctx.beginPath();
                ctx.arc(p.position.x, p.position.y, p.circleRadius, 0, 2 * Math.PI);

                if (p.isPushedBack) {
                    ctx.fillStyle = '#f87171'; // Red for back-EMF
                } else {
                    const speed = Math.sqrt(p.velocity.x ** 2 + p.velocity.y ** 2);
                    if (speed > 4) ctx.fillStyle = '#bae6fd';
                    else if (speed > 1.5) ctx.fillStyle = '#38bdf8';
                    else ctx.fillStyle = '#0284c7';
                }
                ctx.fill();
            }

            ctx.restore();

            // Edge fades
            ctx.save();
            const gradL = ctx.createLinearGradient(visLeft, 0, visLeft + 80, 0);
            gradL.addColorStop(0, '#0a1e3d');
            gradL.addColorStop(1, 'rgba(10,30,61,0)');
            ctx.fillStyle = gradL;
            ctx.fillRect(visLeft, innerTop + wv / 2, 80, innerBottom - innerTop - wv);

            const gradR = ctx.createLinearGradient(visRight - 80, 0, visRight, 0);
            gradR.addColorStop(0, 'rgba(10,30,61,0)');
            gradR.addColorStop(1, '#0a1e3d');
            ctx.fillStyle = gradR;
            ctx.fillRect(visRight - 80, innerTop + wv / 2, 80, innerBottom - innerTop - wv);
            ctx.restore();
        },

        drawHUD: function (ctx, canvas) {
            const cx = canvas.width / 2;
            const cy = canvas.height / 2;
            const supplyV = State.pumpPressure;
            const bemf = this.backEMF;
            const netV = Math.max(0, supplyV - bemf);

            ctx.save();
            ctx.translate(cx + 75, cy - 130);

            // Panel background
            const panelW = 160;
            const panelH = 145;
            ctx.fillStyle = 'rgba(15, 23, 42, 0.9)';
            ctx.strokeStyle = 'rgba(56, 189, 248, 0.5)';
            ctx.lineWidth = 1;
            ctx.beginPath();
            ctx.roundRect(0, 0, panelW, panelH, 10);
            ctx.fill();
            ctx.stroke();

            // Title
            ctx.fillStyle = '#94a3b8';
            ctx.font = '10px "Inter", sans-serif';
            ctx.fillText('MOTOR BACK-EMF', 8, 15);
            ctx.strokeStyle = 'rgba(56, 189, 248, 0.3)';
            ctx.beginPath(); ctx.moveTo(8, 20); ctx.lineTo(panelW - 8, 20); ctx.stroke();

            // RPM
            ctx.font = 'bold 18px "Inter", monospace';
            ctx.fillStyle = '#38bdf8';
            ctx.fillText(`${this.rpm} RPM`, 8, 42);

            // Metrics rows
            const rows = [
                { label: 'V supply', value: `${supplyV.toFixed(0)}`, color: '#4ade80' },
                { label: 'V back-EMF', value: `${bemf.toFixed(1)}`, color: '#f87171' },
                { label: 'V net', value: `${netV.toFixed(1)}`, color: '#fbbf24' },
                { label: 'Load', value: `${this.loadTorque}%`, color: '#a78bfa' },
            ];

            let rowY = 58;
            ctx.font = '10px "Inter", sans-serif';
            for (const row of rows) {
                ctx.fillStyle = '#94a3b8';
                ctx.fillText(row.label, 8, rowY);
                ctx.fillStyle = row.color;
                ctx.font = 'bold 12px "Inter", monospace';
                ctx.fillText(row.value, panelW - 45, rowY);
                ctx.font = '10px "Inter", sans-serif';
                rowY += 19;
            }

            // Back-EMF bar
            const barY = panelH - 16;
            const barW = panelW - 16;
            const fillRatio = Math.min(1, bemf / Math.max(1, supplyV));
            ctx.fillStyle = '#1e293b';
            ctx.beginPath(); ctx.roundRect(8, barY, barW, 6, 3); ctx.fill();

            const barGrad = ctx.createLinearGradient(8, 0, 8 + barW * fillRatio, 0);
            barGrad.addColorStop(0, '#4ade80');
            barGrad.addColorStop(0.5, '#fbbf24');
            barGrad.addColorStop(1, '#f87171');
            ctx.fillStyle = barGrad;
            ctx.beginPath(); ctx.roundRect(8, barY, barW * fillRatio, 6, 3); ctx.fill();

            ctx.restore();
        },

        drawHousing: function (ctx, canvas) {
            const cx = canvas.width / 2;
            const cy = canvas.height / 2;
            ctx.save();
            ctx.beginPath();
            ctx.arc(cx, cy, 110, 0, Math.PI * 2);
            ctx.fillStyle = 'rgba(15, 52, 96, 0.4)';
            ctx.fill();
            ctx.strokeStyle = 'rgba(56, 189, 248, 0.4)';
            ctx.lineWidth = 1.5;
            ctx.setLineDash([15, 10]);
            ctx.stroke();
            ctx.restore();
        },

        drawNozzle: function (ctx) {
            ctx.save();
            ctx.fillStyle = 'rgba(30, 58, 138, 0.9)';
            ctx.strokeStyle = '#60a5fa';
            ctx.lineWidth = 1;
            for (const block of this.nozzle) {
                const pos = block.position;
                ctx.save();
                ctx.translate(pos.x, pos.y);
                ctx.rotate(block.angle);
                ctx.beginPath();
                ctx.roundRect(-12, -4, 24, 8, 2);
                ctx.fill();
                ctx.stroke();
                ctx.restore();
            }
            if (this.shroud) {
                const pos = this.shroud.position;
                ctx.save();
                ctx.translate(pos.x, pos.y);
                ctx.rotate(this.shroud.angle);
                ctx.fillStyle = '#1e293b';
                ctx.beginPath();
                ctx.roundRect(-30, -22, 60, 45, 8);
                ctx.fill();
                ctx.stroke();
                ctx.restore();
            }
            ctx.restore();
        },

        drawWheel: function (ctx, x, y) {
            const speed = Math.abs(this.wheelBody.angularVelocity);
            ctx.save();
            ctx.translate(x, y);
            ctx.rotate(this.wheelBody.angle);

            const NUM_BLADES = 6;
            const INNER_RADIUS = 20;
            const BLADE_LENGTH = 38;
            const BLADE_WIDTH = 10;

            for (let i = 0; i < NUM_BLADES; i++) {
                const angle = (i / NUM_BLADES) * Math.PI * 2;

                // Motion blur arcs
                if (speed > 0.05) {
                    ctx.save();
                    ctx.rotate(angle);
                    ctx.beginPath();
                    const streakLen = speed * 1800;
                    ctx.arc(0, 0, INNER_RADIUS + BLADE_LENGTH + 6, -streakLen / 1000, 0, false);
                    ctx.strokeStyle = `rgba(56, 189, 248, ${Math.min(0.35, speed * 2)})`;
                    ctx.lineWidth = 3;
                    ctx.stroke();
                    ctx.restore();
                }

                ctx.save();
                ctx.rotate(angle);

                ctx.beginPath();
                ctx.roundRect(INNER_RADIUS, -BLADE_WIDTH / 2, BLADE_LENGTH, BLADE_WIDTH, 4);

                const grad = ctx.createLinearGradient(INNER_RADIUS, 0, INNER_RADIUS + BLADE_LENGTH, 0);
                grad.addColorStop(0, '#0369a1');
                grad.addColorStop(0.6, '#0ea5e9');
                grad.addColorStop(1, '#bae6fd');
                ctx.fillStyle = grad;
                ctx.fill();
                ctx.strokeStyle = 'rgba(255, 255, 255, 0.4)';
                ctx.lineWidth = 1;
                ctx.stroke();

                // Tip spark
                if (speed > 0.08) {
                    ctx.translate(INNER_RADIUS + BLADE_LENGTH, 0);
                    ctx.shadowBlur = 12 * speed;
                    ctx.shadowColor = '#38bdf8';
                    ctx.fillStyle = '#ffffff';
                    ctx.beginPath(); ctx.arc(0, 0, 3 * speed, 0, Math.PI * 2); ctx.fill();
                }
                ctx.restore();
            }

            const hubGrad = ctx.createRadialGradient(0, 0, 0, 0, 0, 32);
            hubGrad.addColorStop(0, '#334155'); hubGrad.addColorStop(0.5, '#1e293b'); hubGrad.addColorStop(1, '#0f172a');
            ctx.beginPath(); ctx.arc(0, 0, 32, 0, Math.PI * 2); ctx.fillStyle = hubGrad; ctx.fill();
            ctx.strokeStyle = '#94a3b8'; ctx.lineWidth = 4; ctx.stroke();
            ctx.shadowBlur = 35; ctx.shadowColor = '#38bdf8';
            ctx.beginPath(); ctx.arc(0, 0, 14, 0, Math.PI * 2); ctx.fillStyle = '#f0f9ff'; ctx.fill();

            ctx.restore();
        },

    });

    window.MicroRenderer = WheelSim;
})();
